# Generated by Django 5.0.6 on 2024-08-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploader',
            name='image',
            field=models.ImageField(upload_to='media/memories'),
        ),
    ]
