# Generated by Django 5.0.6 on 2024-08-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_imageuploader_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploader',
            name='image',
            field=models.ImageField(upload_to='memories'),
        ),
    ]
